### ISSUE TITLE
crond: can't execute '/bin/bash' for user root

### ISSUE THREAD

**Issue by charleszlu** [adferrand/docker-letsencrypt-dns#48] opened 2019-05-14 05:14 UTC
Hi Adrien,

The cronjob does not run properly for me on the latest release 2.12.0, and is giving the following error in docker log:

`2019-05-13 13:12:00 [18] | crond: can't execute '/bin/bash' for user root`
`2019-05-14 01:12:00 [18] | crond: can't execute '/bin/bash' for user root`

I have resolved it by adding the `bash` package to the Dockerfile.

Let me know if you would like a PR.

Charles

**Comment by adferrand** [comment] 2019-05-14 10:17
I could not reproduce your problem, but installing `bash` is anyway really useful, in particular with arbitrary scripts that can be executed now using `DEPLOY_HOOK`.

And now `bash` is installed thanks to your PR #47, so I close the issue.

**Closed by adferrand** 2019-05-14 10:17 UTC
